service: myservice

frameworkVersion: '2.4.0'

# serverless-localstack config -->
plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: http://localhost 
    edgePort: 4566
    autostart: false
    lambda:
      mountCode: false
    docker:
      sudo: false
    debug: true
# <-- serverless-localstack config

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    AWS_HOST: http://${env:DOCKER_GATEWAY_HOST, 'host.docker.internal'}:4566

functions:
  hello:
    handler: handler.hello
    # expose to gateway -->
    events:
      - http: GET hello
    # <-- expose to gateway
